package com.cn.hnust.pojo;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_t.id
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_t.user_name
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_t.password
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_t.age
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_t.id
     *
     * @return the value of teacher_t.id
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_t.id
     *
     * @param id the value for teacher_t.id
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_t.user_name
     *
     * @return the value of teacher_t.user_name
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_t.user_name
     *
     * @param userName the value for teacher_t.user_name
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_t.password
     *
     * @return the value of teacher_t.password
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_t.password
     *
     * @param password the value for teacher_t.password
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_t.age
     *
     * @return the value of teacher_t.age
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_t.age
     *
     * @param age the value for teacher_t.age
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}