package com.cn.hnust.dao;

import com.cn.hnust.pojo.Teacher;
import com.cn.hnust.pojo.TeacherTExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ITeacherDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_t
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    int countByExample(TeacherTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_t
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    int deleteByExample(TeacherTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_t
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_t
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_t
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    int insertSelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_t
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    List<Teacher> selectByExample(TeacherTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_t
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    Teacher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_t
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") Teacher record, @Param("example") TeacherTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_t
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    int updateByExample(@Param("record") Teacher record, @Param("example") TeacherTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_t
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    int updateByPrimaryKeySelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_t
     *
     * @mbggenerated Tue Aug 16 23:00:55 CST 2016
     */
    int updateByPrimaryKey(Teacher record);
}